//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models.Entity   //bos deger girilmesin diye
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLKATEGORILER
    {
        [Required(ErrorMessage = "Kategori adi giriniz")]//bos deger girilmesin diye
        public string KATEGORIAD { get; set; }

        public int KATEGORIID { get; set; }
    }
}
